#!/usr/bin/env python3
"""Turns the line icons in svg/ into LVGL alpha images, one .c file per icon.

The images only carry coverage (LV_IMG_CF_ALPHA_8BIT), so the UI tints them
with img_recolor. Each icon comes out at every size in SIZES, named
glyph_<name>_<size>.

Needs rsvg-convert (brew install librsvg) and Pillow.
"""
import pathlib
import subprocess
import tempfile

from PIL import Image

SIZES = [22, 24]
HERE = pathlib.Path(__file__).parent


def rasterize(svg, size):
    with tempfile.NamedTemporaryFile(suffix=".png") as png:
        subprocess.run(["rsvg-convert", "-w", str(size), "-h", str(size), "-o", png.name, str(svg)], check=True)
        return Image.open(png.name).convert("RGBA").getchannel("A")


def c_image(name, alpha):
    w, h = alpha.size
    data = list(alpha.getdata())
    rows = []
    for i in range(0, len(data), 16):
        rows.append("    " + ", ".join(f"0x{v:02x}" for v in data[i:i + 16]) + ",")
    return f"""const LV_ATTRIBUTE_MEM_ALIGN uint8_t {name}_map[] = {{
{chr(10).join(rows)}
}};

const lv_img_dsc_t {name} = {{
    .header = {{
        .cf = LV_IMG_CF_ALPHA_8BIT,
        .always_zero = 0,
        .reserved = 0,
        .w = {w},
        .h = {h},
    }},
    .data_size = {w * h},
    .data = {name}_map,
}};
"""


def main():
    names = []
    for svg in sorted((HERE / "svg").glob("*.svg")):
        parts = ["// Generated by convert.py from svg/" + svg.name + ". Don't edit.", '#include "lvgl.h"', ""]
        for size in SIZES:
            name = f"glyph_{svg.stem}_{size}"
            names.append(name)
            parts.append(c_image(name, rasterize(svg, size)))
        (HERE / f"glyph_{svg.stem}.c").write_text("\n".join(parts))

    header = ["// Generated by convert.py. Don't edit.", "#pragma once", '#include "lvgl.h"', ""]
    header += [f"LV_IMG_DECLARE({name});" for name in names]
    (HERE / "glyphs.h").write_text("\n".join(header) + "\n")


if __name__ == "__main__":
    main()
