#!/usr/bin/env python3
"""Turns the line icons in svg/ into LVGL alpha images, one .c file per icon,
plus glow_240, a soft radial falloff the Lights screen tints.

The images only carry coverage (LV_IMG_CF_ALPHA_8BIT), so the UI tints them
with img_recolor. Each icon comes out at every size in SIZES, named
glyph_<name>_<size>.

Needs rsvg-convert (brew install librsvg) and Pillow.
"""
import pathlib
import subprocess
import tempfile

from PIL import Image

SIZES = [22, 24]
BAYER = [[0, 8, 2, 10], [12, 4, 14, 6], [3, 11, 1, 9], [15, 7, 13, 5]]
HERE = pathlib.Path(__file__).parent


def rasterize(svg, size):
    with tempfile.NamedTemporaryFile(suffix=".png") as png:
        subprocess.run(["rsvg-convert", "-w", str(size), "-h", str(size), "-o", png.name, str(svg)], check=True)
        return Image.open(png.name).convert("RGBA").getchannel("A")


def c_image(name, alpha):
    w, h = alpha.size
    data = list(alpha.getdata())
    rows = []
    for i in range(0, len(data), 16):
        rows.append("    " + ", ".join(f"0x{v:02x}" for v in data[i:i + 16]) + ",")
    return f"""const LV_ATTRIBUTE_MEM_ALIGN uint8_t {name}_map[] = {{
{chr(10).join(rows)}
}};

const lv_img_dsc_t {name} = {{
    .header = {{
        .cf = LV_IMG_CF_ALPHA_8BIT,
        .always_zero = 0,
        .reserved = 0,
        .w = {w},
        .h = {h},
    }},
    .data_size = {w * h},
    .data = {name}_map,
}};
"""


def radial_glow(size):
    """A soft round falloff, full in the middle and gone at the edge."""
    glow = Image.new("L", (size, size))
    px = glow.load()
    c = (size - 1) / 2
    for y in range(size):
        for x in range(size):
            r = ((x - c) ** 2 + (y - c) ** 2) ** 0.5 / (size / 2)
            # A little ordered noise breaks up the rings RGB565 would show.
            noise = BAYER[y % 4][x % 4] / 16 - 0.5
            px[x, y] = max(0, min(255, round(255 * max(0.0, 1 - r) ** 1.6 + noise * 6)))
    return glow


def main():
    names = ["glow_240"]
    (HERE / "glow_240.c").write_text("\n".join([
        "// Generated by convert.py. Don't edit.", '#include "lvgl.h"', "", c_image("glow_240", radial_glow(240))]))
    for svg in sorted((HERE / "svg").glob("*.svg")):
        parts = ["// Generated by convert.py from svg/" + svg.name + ". Don't edit.", '#include "lvgl.h"', ""]
        for size in SIZES:
            name = f"glyph_{svg.stem}_{size}"
            names.append(name)
            parts.append(c_image(name, rasterize(svg, size)))
        (HERE / f"glyph_{svg.stem}.c").write_text("\n".join(parts))

    header = ["// Generated by convert.py. Don't edit.", "#pragma once", '#include "lvgl.h"', ""]
    header += [f"LV_IMG_DECLARE({name});" for name in names]
    (HERE / "glyphs.h").write_text("\n".join(header) + "\n")


if __name__ == "__main__":
    main()
