// Generated by convert.py. Don't edit.
#pragma once
#include "lvgl.h"

LV_IMG_DECLARE(glyph_app_22);
LV_IMG_DECLARE(glyph_app_24);
LV_IMG_DECLARE(glyph_blinds_22);
LV_IMG_DECLARE(glyph_blinds_24);
LV_IMG_DECLARE(glyph_climate_22);
LV_IMG_DECLARE(glyph_climate_24);
LV_IMG_DECLARE(glyph_lights_22);
LV_IMG_DECLARE(glyph_lights_24);
LV_IMG_DECLARE(glyph_music_22);
LV_IMG_DECLARE(glyph_music_24);
LV_IMG_DECLARE(glyph_settings_22);
LV_IMG_DECLARE(glyph_settings_24);
LV_IMG_DECLARE(glyph_speaker_22);
LV_IMG_DECLARE(glyph_speaker_24);
LV_IMG_DECLARE(glyph_stopwatch_22);
LV_IMG_DECLARE(glyph_stopwatch_24);
LV_IMG_DECLARE(glyph_switch_22);
LV_IMG_DECLARE(glyph_switch_24);
